[project]
name = "fake"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flask>=3.1.1",
    "insightface>=0.7.3",
    "numpy>=2.3.2",
    "opencv-python>=4.11.0.86",
]
